spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:{port}/{name}?createDatabaseIfNotExist=true
    username: username
    password: password
  #  JPA Properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true
    #        generate_statistics: true
    #        metadata_builder_contributor: course.hibernate.spring.util.SqlFunctionsMetadataBuilderContributor
    hibernate:
      ddl-auto: update
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: info, health, mappings, metrics, threaddump, heapdump, shutdown, beans, logfile, loggers
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
      cache:
        time-to-live: -1
  info:
    defaults:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
info:
  app:
    encoding: "UTF-8"
    name: REST MVC Demo
    description: REST MVC demo with Spring Boot and Spring Data JPA
    version: 1.0-SNAPSHOT

environments:
  mail-properties:
    test:
      username: "username"
      password: "password"
  default-headmaster-account:
    credentials:
      email: "email@test.com"
      password: "password"
    details:
      first-name: "first name"
      last-name: "last name"
      gender: "gender"
  init-data:
    value: false
logging:
  level:
    org.hibernate.SQL: info
    root: INFO
    course:
      spring:
        intro: DEBUG
    org:
      springframework:
        test:
          context:
            support: INFO
      hibernate:
#        type: trace
#        stat: debug

jwt:
  secret: ${JWT_SECRET:not_a_secret}

