POST /api/schoolyears HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive


###

POST /api/schoolyears HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive


###

POST /api/schoolyears HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/homework HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "description": "What is Animal?",
  "subject": "Biology"
}

###

POST /api/homework HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "description": "What is Atom?",
  "subject": "Physics"
}

###

POST /api/homework HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "description": "5 + 5?",
  "subject": "Mathematics"
}

###

POST /api/homework HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "description": "What is the author of Romeo and Juliet? Choose between William Shakespeare and Hamnet Shakespeare?",
  "subject": "Literature"
}

###

POST /api/homework HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "description": "When was the Declaration of Independence signed?",
  "subject": "History"
}

###

POST /api/schoolyears/1/homework?id=1 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/1/homework?id=2 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/homework?id=3 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/homework?id=4 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/homework?id=5 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/homework?id=6 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/homework?id=1 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
"title": "School year 1 Timetable",
"contentUrl": "https://www.timetables.com/schoolyears/1"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
"title": "School year 2 Timetable",
"contentUrl": "https://www.timetables.com/schoolyears/2"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
"title": "School year 3 Timetable",
"contentUrl": "https://www.timetables.com/schoolyears/3"
}

###

POST /api/schoolyears/1/timetable?timetableId=1 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/timetable?timetableId=2 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/timetable?timetableId=3 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/1/subjects?subject=Biology HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/1/subjects?subject=Physics HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/subjects?subject=Mathematics HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/subjects?subject=Literature HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/subjects?subject=History HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/subjects?subject=Biology HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Ivan",
  "lastName": "Petrov",
  "email": "test1@gmail.com",
  "gender": "MALE",
  "subject": "Biology",
  "role": "TEACHER"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Ivan",
  "lastName": "Draganov",
  "email": "test2@gmail.com",
  "gender": "MALE",
  "subject": "Physics",
  "role": "TEACHER"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Anna",
  "lastName": "Smith",
  "email": "test3@gmail.com",
  "gender": "FEMALE",
  "subject": "Mathematics",
  "role": "TEACHER"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "test4@gmail.com",
  "gender": "MALE",
  "subject": "Literature",
  "role": "TEACHER"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Peter",
  "lastName": "Christoph",
  "email": "test5@gmail.com",
  "gender": "MALE",
  "subject": "History",
  "role": "TEACHER"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Silvia",
  "lastName": "Grozdeva",
  "email": "test6@gmail.com",
  "gender": "FEMALE",
  "subject": "Biology",
  "role": "TEACHER"
}

###

POST /api/schoolyears/1/teachers?id=1 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/1/teachers?id=2 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/teachers?id=3 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/teachers?id=4 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/teachers?id=5 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/teachers?id=6 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "George",
  "lastName": "Samson",
  "email": "test7@gmail.com",
  "gender": "MALE",
  "role": "STUDENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Iveta",
  "lastName": "Wells",
  "email": "test8@gmail.com",
  "gender": "FEMALE",
  "role": "STUDENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Galadriel",
  "lastName": "Alatariel",
  "email": "lorienCity@gmail.com",
  "gender": "FEMALE",
  "role": "STUDENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Elrond",
  "lastName": "Peredhel",
  "email": "test10@gmail.com",
  "gender": "MALE",
  "role": "STUDENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Arwen",
  "lastName": "Elerondiel",
  "email": "test11@gmail.com",
  "gender": "FEMALE",
  "role": "STUDENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Eldarion",
  "lastName": "King of the Reunited Kingdom",
  "email": "test12@gmail.com",
  "gender": "MALE",
  "role": "STUDENT"
}

###

POST /api/schoolyears/1/students?id=7 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/1/students?id=8 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/students?id=9 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/students?id=10 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/students?id=11 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/students?id=12 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/exams HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "subject": "Physics",
  "content": "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."
}

###

POST /api/exams HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "subject": "Literature",
  "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
}

###

POST /api/exams HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "subject": "History",
  "content": "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."
}

###

POST /api/schoolyears/1/exams?id=1 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/2/exams?id=2 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/schoolyears/3/exams?id=3 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "title": "Personal timetable for Ivan Petrov",
  "contentUrl": "https://testTimetable.com/teachers/1"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "title": "Personal timetable for Ivan Draganov",
  "contentUrl": "https://testTimetable.com/teachers/2"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "title": "Personal timetable for Anna Smith",
  "contentUrl": "https://testTimetable.com/teachers/3"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "title": "Personal timetable for John Smith",
  "contentUrl": "https://testTimetable.com/teachers/4"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "title": "Personal timetable for Peter Christoph",
  "contentUrl": "https://testTimetable.com/teachers/5"
}

###

POST /api/timetables HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "title": "Personal timetable for Silvia Grozdeva",
  "contentUrl": "https://testTimetable.com/teachers/6"
}

###

POST /api/teachers/1/timetable?id=1 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/teachers/2/timetable?id=2 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/teachers/3/timetable?id=3 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/teachers/4/timetable?id=4 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/teachers/5/timetable?id=5 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/teachers/6/timetable?id=6 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/homework/1/results?studentId=8 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

Animals are multicellular, eukaryotic organisms in the biological kingdom Animalia. With few exceptions, animals consume organic material, breathe oxygen, are able to move, can reproduce sexually, and go through an ontogenetic stage in which their body consists of a hollow sphere of cells, the blastula, during embryonic development.

###

POST /api/homework/1/results?studentId=12 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

I don't know what an animal is.

###

POST /api/homework/3/results?studentId=10 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

10

###

POST /api/homework/5/results?studentId=11 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

The Continental Congress adopted the Declaration of Independence on July 4, 1776. It was engrossed on parchment and on August 2, 1776, delegates began signing it.

###

POST /api/homework/1/results/8?grade=6.00 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/homework/1/results/12?grade=2.00 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/homework/3/results/10?grade=5.70 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/homework/5/results/11?grade=5.90 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/certificates HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "imageUrl": "https://www.testCertificate.com/certificates/1"
}

###

POST /api/certificates HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "imageUrl": "https://www.testCertificate.com/certificates/2"
}

###

POST /api/certificates/1/owner?userId=7 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Isildur",
  "lastName": "King of Gondor",
  "email": "roaylGondorKing@gmail.com",
  "gender": "MALE",
  "role": "PARENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Elendil",
  "lastName": "The Fair",
  "email": "numenor77@gmail.com",
  "gender": "MALE",
  "role": "PARENT"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Celeborn",
  "lastName": "Lord of the Galadhrim",
  "email": "royalHouseOfDoriath@gmail.com",
  "gender": "MALE",
  "role": "PARENT"
}

###

POST /api/parents/13/children?studentId=7 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/parents/13/children?studentId=8 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/parents/14/children?studentId=9 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/parents/14/children?studentId=10 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/parents/15/children?studentId=12 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/exams/1/performers?studentId=7 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

This is my answer for this exam. Thank you.

###

POST /api/exams/1/performers?studentId=7 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

This is my answer for this exam. Thank you.

###

POST /api/exams/2/performers?studentId=9 HTTP/1.1
Content-Type: text/plain
Accept: */*
Host: localhost:8080
Connection: keep-alive

I don't know what to type as a result for this exam.

###

POST /api/exams/1/results?studentId=7&grade=5.00 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/exams/2/results?studentId=9&grade=3.50 HTTP/1.1
Accept: */*
Host: localhost:8080
Connection: keep-alive

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Dwalin",
  "lastName": "Lord of the Lonely Mountain",
  "email": "dwalin32@gmail.com",
  "gender": "MALE",
  "role": "HEADMASTER"
}

###

POST /api/users HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "firstName": "Smaug",
  "lastName": "The Golden",
  "email": "lordDragon@gmail.com",
  "gender": "MALE",
  "role": "HEADMASTER"
}

###

POST /api/competitions HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "startDay": "23",
  "startMonth": "9",
  "startYear": "2022",
  "startHour": "11",
  "startMinutes": "29",
  "endDay": "23",
  "endMonth": "9",
  "endHour": "11",
  "endMinutes": "31",
  "questions": [
    {
      "title": "test question1",
      "answers": "1) 123, 2) 523, 3) 313, 4) 212",
      "realAnswer": 1
    },
    {
      "title": "test question2",
      "answers": "1) test, 2) test, 3) test, 4) test",
      "realAnswer": 2
    },
    {
      "title": "test question3",
      "answers": "1) test, 2) test, 3) test, 4) test",
      "realAnswer": 3
    }
  ],
  "pointsPerQuestion": 10
}

###

POST /api/competitions HTTP/1.1
Content-Type: application/json
Accept: */*
Host: localhost:8080
Connection: keep-alive

{
  "startDay": "24",
  "startMonth": "12",
  "startYear": "2022",
  "startHour": "12",
  "startMinutes": "29",
  "endDay": "25",
  "endMonth": "12",
  "endHour": "11",
  "endMinutes": "31",
  "questions": [
    {
      "title": "test question1",
      "answers": "1) abc, 2) dca, 3) abvs, 4) mnb",
      "realAnswer": 3
    },
    {
      "title": "test question2",
      "answers": "1) zxc, 2) nbv, 3) cpo, 4) oop",
      "realAnswer": 2
    },
    {
      "title": "test question3",
      "answers": "1) zaq, 2) qwe, 3) wsx, 4) rsd",
      "realAnswer": 2
    }
  ],
  "pointsPerQuestion": 15
}

